name: Analyze code statically
"on": [pull_request]
jobs:
  gosec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Analyze code statically using gosec
        run: |
          echo "::add-matcher::.github/workflows/gosec-problem-matcher.json"
          go get github.com/securego/gosec/v2/cmd/gosec
          gosec -quiet -fmt=golint ./...
