---
name: Analyze code statically
"on": [push, pull_request]
jobs:
  gosec:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
      - run: echo "$GOPATH/bin" >> $GITHUB_PATH
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: |
          curl -sSfL https://raw.githubusercontent.com/securego/gosec/master/install.sh |
           sh -s -- -b $(go env GOPATH)/bin
      - run: gosec -no-fail -fmt sarif -out results.sarif ./...
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
