---
name: SAST
"on": [pull_request, workflow_dispatch]
jobs:
  gosec:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
      - run: echo "$GOPATH/bin" >> $GITHUB_PATH
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: |
          curl -sSfL https://raw.githubusercontent.com/securego/gosec/master/install.sh |
           sh -s -- -b $(go env GOPATH)/bin
           gosec -version
        name: Install gosec (latest release version)
      - run: |
           pushd ..
           git clone https://github.com/securego/gosec.git
           cd gosec
           make
           cp gosec $GOPATH/bin
           popd
           gosec -version
        name: Install gosec (master branch version)
      - run: gosec -no-fail -fmt sarif -out gosec.sarif ./...
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: gosec.sarif
